version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-site"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lreqic7455z2"
s3_prefix = "resume-site"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
